# Generated by Django 4.2.7 on 2025-05-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên ca')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('break_time', models.PositiveIntegerField(default=0, verbose_name='Thời gian nghỉ (phút)')),
                ('working_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Giờ công')),
                ('normal_day_coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Hệ số ngày thường')),
                ('rest_day_coefficient', models.DecimalField(decimal_places=2, default=1.5, max_digits=3, verbose_name='Hệ số ngày nghỉ')),
                ('holiday_coefficient', models.DecimalField(decimal_places=2, default=2.0, max_digits=3, verbose_name='Hệ số ngày lễ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên thành phần')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền')),
                ('component_type', models.CharField(max_length=50, verbose_name='Loại thành phần')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('payroll_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='attendance.payrolltemplate', verbose_name='Mẫu bảng lương')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên bảng chấm công')),
                ('month', models.PositiveIntegerField(verbose_name='Tháng')),
                ('year', models.PositiveIntegerField(verbose_name='Năm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('attendance_type', models.CharField(choices=[('daily', 'Theo ngày'), ('shift', 'Theo ca')], default='daily', max_length=10, verbose_name='Hình thức chấm công')),
                ('standard_workdays', models.PositiveIntegerField(default=22, verbose_name='Số công chuẩn')),
                ('paid_leave', models.PositiveIntegerField(default=0, verbose_name='Công nghỉ chế độ')),
                ('approved_leave', models.PositiveIntegerField(default=0, verbose_name='Nghỉ có phép')),
                ('unapproved_leave', models.PositiveIntegerField(default=0, verbose_name='Nghỉ không phép')),
                ('is_transferred', models.BooleanField(default=False, verbose_name='Đã chuyển tính lương')),
                ('positions', models.ManyToManyField(to='employees.position', verbose_name='Vị trí áp dụng')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('status', models.CharField(choices=[('present', 'Có mặt'), ('absent', 'Vắng mặt'), ('late', 'Đi muộn'), ('leave', 'Nghỉ phép')], max_length=10, verbose_name='Trạng thái')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Giờ vào')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Giờ ra')),
                ('working_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Số giờ làm việc')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesheet')),
                ('work_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.workshift', verbose_name='Ca làm việc')),
            ],
        ),
    ]
