# Generated by Django 4.2.7 on 2025-05-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='name',
            field=models.CharField(default='Bảng chấm công', max_length=100, verbose_name='Tên bảng chấm công'),
            preserve_default=False,
        ),
    ]
