# Generated by Django 4.2.8 on 2025-05-08 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày chấm công')),
                ('paid_work_days', models.FloatField(default=1, verbose_name='Số công hưởng lương')),
                ('actual_work_days', models.FloatField(default=1, verbose_name='Số công đi làm thực tế')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='Giờ vào')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='Giờ ra')),
                ('attendance_status', models.CharField(choices=[('not_absent', 'Không nghỉ'), ('permitted_absence', 'Nghỉ có phép'), ('unpermitted_absence', 'Nghỉ không phép'), ('regime_absence', 'Nghỉ theo chế độ')], default='not_absent', max_length=20, verbose_name='Nghỉ')),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='attendance.attendancerecord', verbose_name='Bảng chấm công')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Nhân viên')),
                ('work_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.workshift', verbose_name='Ca làm việc')),
            ],
            options={
                'verbose_name': 'Chấm công hàng ngày',
                'verbose_name_plural': 'Chấm công hàng ngày',
                'unique_together': {('attendance_record', 'employee', 'date')},
            },
        ),
    ]
