# Generated by Django 4.2.7 on 2025-05-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_date',
            field=models.DateField(null=True, verbose_name='Ngày'),
        ),
    ]
