# Generated by Django 4.2.8 on 2025-05-08 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('attendance', '0002_dailyattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên bảng chấm công tổng hợp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_records', models.ManyToManyField(to='attendance.attendancerecord', verbose_name='Danh sách bảng chấm công chi tiết')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Vị trí áp dụng')),
            ],
            options={
                'verbose_name': 'Bảng chấm công tổng hợp',
                'verbose_name_plural': 'Các bảng chấm công tổng hợp',
                'ordering': ['-created_at'],
            },
        ),
    ]
