# Generated by Django 4.2.7 on 2025-05-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã đơn vị')),
                ('name', models.CharField(max_length=100, verbose_name='Tên đơn vị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã nhân viên')),
                ('first_name', models.CharField(max_length=50, verbose_name='Tên')),
                ('last_name', models.CharField(max_length=50, verbose_name='Họ')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, verbose_name='Giới tính')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='Số CMND/CCCD')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('join_date', models.DateField(verbose_name='Ngày vào làm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang làm việc')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='Ảnh')),
                ('labor_status', models.CharField(choices=[('working', 'Đang làm việc'), ('retired', 'Đã nghỉ việc')], default='working', max_length=20, verbose_name='Trạng thái lao động')),
                ('employment_type', models.CharField(choices=[('official', 'Chính thức'), ('probation', 'Thử việc'), ('intern', 'Học việc'), ('temporary', 'Tạm thời'), ('other', 'Khác')], default='official', max_length=20, verbose_name='Tính chất lao động')),
                ('contract_type', models.CharField(blank=True, choices=[('probation', 'Thử việc'), ('definite', 'Hợp đồng xác định thời hạn'), ('indefinite', 'Hợp đồng không xác định thời hạn'), ('seasonal', 'Hợp đồng mùa vụ'), ('service', 'Hợp đồng dịch vụ')], max_length=20, null=True, verbose_name='Loại hợp đồng')),
                ('dependents', models.IntegerField(default=0, verbose_name='Số người phụ thuộc')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department')),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Công ty')),
                ('position', models.CharField(max_length=100, verbose_name='Vị trí')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả công việc')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_histories', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(verbose_name='Ngày hiệu lực')),
                ('old_salary', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Lương cũ')),
                ('new_salary', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Lương mới')),
                ('reason', models.TextField(verbose_name='Lý do thay đổi')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_histories', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã vị trí')),
                ('name', models.CharField(max_length=100, verbose_name='Tên vị trí')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_positions', to='employees.department')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.position', verbose_name='Vị trí công việc'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('probation', 'Thử việc'), ('definite', 'Xác định thời hạn'), ('indefinite', 'Không xác định thời hạn')], max_length=20, verbose_name='Loại hợp đồng')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('basic_salary', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Lương cơ bản')),
                ('insurance_salary', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Lương đóng bảo hiểm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiệu lực')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employees.employee')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_contracts', to='employees.position')),
            ],
        ),
    ]
