# Generated by Django 4.2.7 on 2025-05-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Toàn thời gian'), ('part_time', 'Bán thời gian'), ('intern', 'Thực tập')], max_length=20, null=True, verbose_name='Loại công việc'),
        ),
    ]
