# Generated by Django 4.2.7 on 2025-05-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã đơn vị')),
                ('name', models.CharField(max_length=100, verbose_name='Tên đơn vị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Mã nhân viên')),
                ('first_name', models.CharField(max_length=50, verbose_name='Tên')),
                ('last_name', models.CharField(max_length=50, verbose_name='Họ')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, verbose_name='Giới tính')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('department', models.CharField(max_length=100, verbose_name='Phòng ban')),
                ('position', models.CharField(max_length=100, verbose_name='Chức vụ')),
                ('hire_date', models.DateField(verbose_name='Ngày vào làm')),
                ('status', models.CharField(choices=[('active', 'Đang làm việc'), ('inactive', 'Đã nghỉ việc'), ('on_leave', 'Đang nghỉ phép'), ('suspended', 'Tạm đình chỉ')], default='active', max_length=20, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('approved', 'Đã duyệt')], default='draft', max_length=20)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt')], default='pending', max_length=20)),
                ('submitted_by', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('paid', 'Đã thanh toán')], default='pending', max_length=20)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Công ty')),
                ('position', models.CharField(max_length=100, verbose_name='Vị trí')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả công việc')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_histories', to='payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(verbose_name='Ngày hiệu lực')),
                ('old_salary', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Lương cũ')),
                ('new_salary', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Lương mới')),
                ('reason', models.TextField(verbose_name='Lý do thay đổi')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_histories', to='payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã vị trí')),
                ('name', models.CharField(max_length=100, verbose_name='Tên vị trí')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_positions', to='employees.department')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('viewed_date', models.DateField(blank=True, null=True)),
                ('payroll_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrolldetail')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('earning', 'Thu nhập'), ('deduction', 'Khấu trừ')], max_length=20)),
                ('calculation_type', models.CharField(choices=[('fixed', 'Cố định'), ('percentage', 'Phần trăm')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payrolltemplate')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('approved', 'Đã duyệt'), ('paid', 'Đã trả lương')], default='draft', max_length=20)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrolltemplate')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('paid', 'Đã thanh toán')], default='pending', max_length=20)),
                ('payment_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollpayment')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollDataDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('payroll_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payroll.payrolldata')),
            ],
        ),
        migrations.AddField(
            model_name='payrolldata',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollperiod'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollperiod'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('probation', 'Thử việc'), ('definite', 'Xác định thời hạn'), ('indefinite', 'Không xác định thời hạn')], max_length=20, verbose_name='Loại hợp đồng')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('basic_salary', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Lương cơ bản')),
                ('insurance_salary', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Lương đóng bảo hiểm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiệu lực')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='payroll.employee')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_contracts', to='employees.position')),
            ],
        ),
    ]
