# Generated by Django 4.2.7 on 2025-05-11 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('approved', 'Đã duyệt')], default='draft', max_length=20)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên thành phần')),
                ('code', models.CharField(max_length=20, verbose_name='Mã thành phần')),
                ('component_type', models.CharField(choices=[('allowance', 'Phụ cấp'), ('bonus', 'Thưởng'), ('deduction', 'Khấu trừ'), ('tax', 'Thuế')], max_length=20, verbose_name='Loại thành phần')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền')),
                ('is_percentage', models.BooleanField(default=False, verbose_name='Là phần trăm')),
                ('is_taxable', models.BooleanField(default=False, verbose_name='Chịu thuế')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt')], default='pending', max_length=20)),
                ('submitted_by', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_workdays', models.PositiveIntegerField(default=22, verbose_name='Số công chuẩn')),
                ('actual_workdays', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Số công thực tế')),
                ('paid_leave', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Nghỉ có phép')),
                ('unpaid_leave', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Nghỉ không phép')),
                ('policy_leave', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Công nghỉ chế độ')),
                ('basic_salary', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Lương cơ bản')),
                ('salary_rate', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Tỉ lệ hưởng lương (%)')),
                ('personal_tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Thuế TNCN (%)')),
                ('personal_tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thuế TNCN')),
                ('personal_deduction', models.DecimalField(decimal_places=0, default=11000000, max_digits=12, verbose_name='Giảm trừ gia cảnh')),
                ('dependent_deduction', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giảm trừ người phụ thuộc')),
                ('dependents', models.PositiveIntegerField(default=0, verbose_name='Số người phụ thuộc')),
                ('deduction', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Khấu trừ')),
                ('performance_bonus', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thưởng hiệu suất')),
                ('gross_income', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng thu nhập')),
                ('net_income', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thực lĩnh')),
                ('overtime_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('working_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grass_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_details', to='employees.employee')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payroll.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('paid', 'Đã thanh toán')], default='pending', max_length=20)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_positions', to='employees.position', verbose_name='Vị trí áp dụng')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('viewed_date', models.DateField(blank=True, null=True)),
                ('payroll_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrolldetail')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('earning', 'Thu nhập'), ('deduction', 'Khấu trừ')], max_length=20)),
                ('calculation_type', models.CharField(choices=[('fixed', 'Cố định'), ('percentage', 'Phần trăm')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payrolltemplate')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('approved', 'Đã duyệt'), ('paid', 'Đã trả lương')], default='draft', max_length=20)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrolltemplate')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('paid', 'Đã thanh toán')], default='pending', max_length=20)),
                ('payment_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollpayment')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollDataDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('payroll_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payroll.payrolldata')),
            ],
        ),
        migrations.AddField(
            model_name='payrolldata',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollperiod'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollperiod'),
        ),
    ]
